/* CONTEXT */
import RootContextProvider from '@/context/RootContext';
/* CSS */
import CssInjector from "@/components/CssInjector";
/* LAYOUT */
import UxContainer from "@/components/layout/UxContainer";
import UxHeader from "@/components/layout/UxHeader";
import UxMain from "@/components/layout/UxMain";
import UxFooter from "@/components/layout/UxFooter";
import UxModal from "@/components/layout/UxModal";

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
	return (
		<html lang="ko">
			<body>
				<CssInjector />
				<RootContextProvider>
					<UxContainer>
						<UxHeader />
						<UxMain>
							{children}
						</UxMain>
						<UxFooter />
					</UxContainer>
					<UxModal />
				</RootContextProvider>
			</body>
		</html>
	)
}